school_app/school_app/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
    
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('school_student.urls')),
    path('school/admin/',include('school_admin.urls')),
    path('school/teacher/',include('school_teacher.urls'))

]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

school_app/school_teacher/urls.py
from django.urls import path
from . import views

app_name = 'teacher'
urlpatterns = [
    path('', views.home, name = 'home'),
    path('add/student', views.add_student, name = 'add_student'),
    path('student/list', views.students_list, name = 'students_list'),
    path('notes/upload', views.upload_notes, name = 'upload_notes'),

     
]

school_app/school_teacher/models.py
from django.db import models

# Create your models here.
class Teacher(models.Model):
    teacher_id = models.IntegerField()
    teacher_name = models.CharField(max_length = 50)
    teacher_class = models.IntegerField()
    division = models.CharField(max_length = 10)
    password = models.CharField(max_length = 30)
    section = models.CharField(max_length = 30)
    
    staff_status = models.CharField(max_length = 20, default = 'active')

    class Meta:
        db_table = "teacher"


class Student(models.Model):
    roll_no = models.IntegerField()
    admission_no = models.IntegerField()
    student_name = models.CharField(max_length = 50)
    student_class = models.IntegerField()
    division = models.CharField(max_length = 10)
    student_status = models.CharField(max_length = 20, default = 'active')
    password = models.CharField(max_length = 30, default = "12345")  
    # status = models.CharField(max_length=20, default = 'active')
    class Meta:
        db_table = "student"

school_app/school_teacher/views.py
from django.shortcuts import render,redirect
from .models import *
from school_student.models import Notes
# Create your views here.
def home(request):
    return render(request,'teacher/home.html')

def add_student(request):
    message = ''
    if request.method == 'POST':
        roll_no = request.POST['roll_no']
        admission_no = request.POST['admissionNo']
        student_name = request.POST['studentName'].lower()

        record = Student.objects.filter(admission_no = admission_no)

        if not record:
            _ = Student(roll_no=roll_no, 
                        admission_no=admission_no,
                         student_class=request.session['teacher_class'],
                         division=request.session['division'],
                         student_name = student_name
                         
                         ).save()
            message = 'Student Added Succesfully '

        else:
            message = 'Admission No Exist'
    return render(request, 'teacher/add_student.html', {'message': message})

def students_list(request):     
    students = Student.objects.filter(
        student_class= request.session['teacher_class'],
        division = request.session['division'],
        status = 'active'
        ).order_by('roll_no')
    return render(request, 'teacher/student_list.html', {'students_list': students})

def upload_notes(request):
    message = ''     
    if request.method =='POST':
        class_st = request.POST['cls']
        descr = request.POST['descr']
        file = request.FILES['file']
        subject = request.POST['sub']
        notes = Notes(
            subject = subject,
            description = descr,
            added_by = request.session['teacher_name'],
            student_cls = class_st,
            file = file

        )
        notes.save()
        message = "Notes added Succesfully"

    return render(request, 'teacher/upload_notes.html',{'message': message})

school_app/school_teacher/templates/teacher/add_student.html
{% extends 'teacher/master.html' %}

{% block content %}
<div class="container d-flex justify-content-center " style="min-height: 100vh;">
    <div class="col-md-6">
        <div class="card-body">
            <h3 class="text-center py-3" style="font-weight: bolder;">Add Student</h3>
             
            {% if message %}
           <div class="alert  mt-3"  style="background-color: #EE4266;color: white;" id="error-msg" role="alert">
            {{ message }}
          </div>
          {% endif %}
            <form method="POST">
                {% csrf_token %}
                <div class="mb-1">
                    <label for="roll_no" class="form-label text-dark py-2">Roll No</label>
                    <input type="number"class="form-control" name="roll_no" id="">
                </div>
                <div class="mb-1">
                    <label for="admission_no" class="form-label text-dark py-2">Admission No</label>
                    <input type="number"class="form-control" name="admissionNo" id="">
                </div>
                
                <div class="mb-1">
                    <label for="studentName" class="form-label text-dark py-2">Student Name</label>
                    <input type="text" class="form-control" name="studentName" id="">
                </div>    
                 
                 
                <div>
                <button type="submit" class="btn btn-primary d-flex justify-content-center w-100">Add Now</button>

                </div>
            </form>

            
        </div>
    </div>
 
 

    <script>
        setTimeout(function() {
           var errorMsg = document.getElementById('error-msg');
           if (errorMsg) {
              errorMsg.style.display = 'none';
           }
        }, 2000); // 5000 milliseconds = 5 seconds
     </script>
</div>
{% endblock %}

school_app/school_teacher/templates/teacher/home.html
{% extends "teacher/master.html" %}

{% block content %}
    <h3 style="font-size: 40px; margin-top: 170px;  margin-left: 300px;">Welcome {{request.session.teacher_name| title}}</h3>
{% endblock %}
 

school_app/school_teacher/templates/teacher/master.html
{% load static %}
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>ERP</title>
    <!-- plugins:css -->
    <link rel="stylesheet" href="{% static 'scl_admin/assets/vendors/feather/feather.css' %}">
    <link rel="stylesheet" href="{% static 'scl_admin/assets/vendors/ti-icons/css/themify-icons.css' %}">
    <link rel="stylesheet" href="{% static 'scl_admin/assets/vendors/css/vendor.bundle.base.css' %}">
    <link rel="stylesheet" href="{% static 'scl_admin/assets/vendors/font-awesome/css/font-awesome.min.css' %}">
    <link rel="stylesheet" href="{% static 'scl_admin/assets/vendors/mdi/css/materialdesignicons.min.css' %}">
    <!-- endinject -->
    <!-- Plugin css for this page -->
    <!-- <link rel="stylesheet" href="assets/vendors/datatables.net-bs4/dataTables.bootstrap4.css"> -->
    <link rel="stylesheet" href="{% static 'scl_admin/assets/vendors/datatables.net-bs5/dataTables.bootstrap5.css' %}">
    <link rel="stylesheet" href="{% static 'scl_admin/assets/vendors/ti-icons/css/themify-icons.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'scl_admin/assets/js/select.dataTables.min.css' %}">
    <!-- End plugin css for this page -->
    <!-- inject:css -->
    <link rel="stylesheet" href="{% static 'scl_admin/assets/css/style.css' %}">
    <!-- endinject -->
    <link rel="shortcut icon" href="{% static 'scl_admin/assets/images/favicon.png' %}" />
  </head>
  <body>
     
      <!-- partial:partials/_navbar.html -->
      <nav class="navbar col-lg-12 col-12 p-0 fixed-top d-flex flex-row">
  <div class="text-center navbar-brand-wrapper d-flex align-items-center justify-content-start">
    <a class="navbar-brand brand-logo me-5" href="index.html"><img src="{% static 'scl_admin/assets/images/logo.svg' %}" class="me-2" alt="logo" /></a>
    <a class="navbar-brand brand-logo-mini" href="index.html"><img src="{% static 'scl_admin/assets/images/logo-mini.svg' %}" alt="logo" /></a>
  </div>
  <div class="navbar-menu-wrapper d-flex align-items-center justify-content-end">
    <button class="navbar-toggler navbar-toggler align-self-center" type="button" data-toggle="minimize">
      <span class="icon-menu"></span>
    </button>
    <ul class="navbar-nav mr-lg-2">
      <li class="nav-item nav-search d-none d-lg-block">
        <div class="input-group">
          <div class="input-group-prepend hover-cursor" id="navbar-search-icon">
            <span class="input-group-text" id="search">
              <i class="icon-search"></i>
            </span>
          </div>
          <input type="text" class="form-control" id="navbar-search-input" placeholder="Search now" aria-label="search" aria-describedby="search">
        </div>
      </li>
    </ul>
    <ul class="navbar-nav navbar-nav-right">
       
       
      <li class="nav-item nav-profile dropdown">
        <a class="nav-link dropdown-toggle" href="#" data-bs-toggle="dropdown" id="profileDropdown">
          <img src="{% static 'scl_admin/assets/images/faces/face28.jpg' %}" alt="profile" />
        </a>
        <div class="dropdown-menu dropdown-menu-right navbar-dropdown" aria-labelledby="profileDropdown">
           
          <a class="dropdown-item">
            <i class="ti-power-off text-primary"></i> Logout </a>
        </div>
      </li>
      <li class="nav-item nav-settings d-none d-lg-flex">
        <a class="nav-link" href="#">
          <i class="icon-ellipsis"></i>
        </a>
      </li>
    </ul>
    <button class="navbar-toggler navbar-toggler-right d-lg-none align-self-center" type="button" data-toggle="offcanvas">
      <span class="icon-menu"></span>
    </button>
  </div>
</nav>
      <!-- partial -->
      <div class="container-fluid page-body-wrapper">
        <!-- partial:partials/_sidebar.html -->
        <nav class="sidebar sidebar-offcanvas" id="sidebar">
  <ul class="nav">
    <li class="nav-item">
      <a class="nav-link" href="{% url 'teacher:home' %}">
        <i class="icon-grid menu-icon"></i>
        <span class="menu-title">Dashboard</span>
      </a>
    </li>
    <li class="nav-item">
      <a class="nav-link"   href="{% url 'teacher:add_student' %}"  >
        <i class="icon-layout menu-icon"></i>
        <span class="menu-title">Add Students</span>
        <i class="menu-arrow"></i>
      </a>
       
    </li>
    <li class="nav-item">
        <a class="nav-link"   href="{% url 'teacher:students_list' %}"  >
          <i class="icon-layout menu-icon"></i>
          <span class="menu-title">Students </span>
          <i class="menu-arrow"></i>
        </a>
         
      </li>

      <li class="nav-item">
        <a class="nav-link"   href="{% url 'teacher:upload_notes' %}" >
          <i class="icon-layout menu-icon"></i>
          <span class="menu-title">Upload Notes </span>
          <i class="menu-arrow"></i>
        </a>
         
      </li>
     
    <li class="nav-item">
      <a class="nav-link" href="../../../docs/documentation.html">
        <i class="icon-paper menu-icon"></i>
        <span class="menu-title">Logout </span>
      </a>
    </li>
  </ul>
</nav>
        <!-- partial -->
        <div class="main-panel">
          <div class="content-wrapper">
            
              
            {% block content %}

            {% endblock %}
             
             
             
             
          </div>
          
        </div>
        <!-- main-panel ends -->
      </div>
      <!-- page-body-wrapper ends -->
    </div>
    <!-- container-scroller -->
    <!-- plugins:js -->
    <script src="{% static 'scl_admin/assets/vendors/js/vendor.bundle.base.js' %}"></script>
    <!-- endinject -->
    <!-- Plugin js for this page -->
    <script src="{% static 'scl_admin/assets/vendors/chart.js/chart.umd.js' %}"></script>
    <script src="{% static 'scl_admin/assets/vendors/datatables.net/jquery.dataTables.js' %}"></script>
    <!-- <script src="{% static 'scl_admin/assets/vendors/datatables.net-bs4/dataTables.bootstrap4.js"></script> -->
    <script src="{% static 'scl_admin/assets/vendors/datatables.net-bs5/dataTables.bootstrap5.js' %}"></script>
    <script src="{% static 'scl_admin/assets/js/dataTables.select.min.js' %}"></script>
    <!-- End plugin js for this page -->
    <!-- inject:js -->
    <script src="{% static 'scl_admin/assets/js/off-canvas.js' %}"></script>
    <script src="{% static 'scl_admin/assets/js/template.js' %}"></script>
    <script src="{% static 'scl_admin/assets/js/settings.js' %}"></script>
    <script src="{% static 'scl_admin/assets/js/todolist.js' %}"></script>
    <!-- endinject -->
    <!-- Custom js for this page-->
    <script src="{% static 'scl_admin/assets/js/jquery.cookie.js' %}" type="text/javascript"></script>
    <script src="{% static 'scl_admin/assets/js/dashboard.js' %}"></script>
    <!-- <script src="assets/js/Chart.roundedBarCharts.js"></script> -->
    <!-- End custom js for this page-->
  </body>
</html>

school_app/school_teacher/templates/teacher/student_list.html
{% extends 'teacher/master.html' %} 
{% block content %}
<div
  class="container "
>
    <div class="row">

            <div class="col-md-12">
                <div class="table-responsive">

                
                <table class="table table-hover  table-primary">
                    <thead>
                        <tr class="text-center ">
                            <th>SL NO</th>
                            <th>Roll No</th>
                            <th>Adm. No</th> 
                            <th>Student Name</th> 

                            
                         
                            
                             
                        </tr>
                    </thead>
                    <tbody>
                        {% for student in students_list %}
                        <tr class="text-center">
                            <td>{{forloop.counter}}</td>
                            <td>{{ student.roll_no }}</td>
                            <td>{{ student.admission_no }}</td>
                            <td>{{ student.student_name | title }}</td>

                            
                
                           
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
            </div>
    </div>
     

    <!-- moral/islamic -->

    <div class="modal fade" id="moralModal" tabindex="-1" aria-labelledby="imageModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered">
            <div class="modal-content">
                <div class="modal-header">
               
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body text-center">
                    
                    <form method="POST">
                        {% csrf_token %}
                        <table style="border-collapse: separate;border-spacing: 10px;">
                            <tr>
                                 
                                <td>
                                    <select name="moralType" style="font-size: 18px;font-weight: bold;" id="" class="form-control">
                                        <option value="moral science">Moral Science</option>
                                        <option value="islamic studies">Islamic Studies</option>
                                    </select>
                                </td>
                            </tr>
                             
                                <td><input type="hidden" name="moralStudentId" id="moralStudentId"></td>
                             
                            <tr>
                                <td></td>
                                <td>
                                    <input class="btn btn-success" type="submit" value="Submit" name="moral" id="">
                                </td>
                            </tr>
                        </table>
                         
                    </form>
                </div>
                 
            </div>
        </div>
    </div>
    
    <!-- moral/islamic --> 

 <!-- second -->

 <div class="modal fade" id="secondModal" tabindex="-1" aria-labelledby="imageModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-header">
           
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body text-center">
                
                <form method="POST">
                    {% csrf_token %}
                    <table style="border-collapse: separate;border-spacing: 10px;">
                        <tr>
                             
                            <td>
                                <select name="secondLanguage" style="font-size: 18px;font-weight: bold;" id="" class="form-control">
                                    <option value="urdu 1">URDU 1</option>
                                    <option value="hindi">Hindi</option>
                                </select>
                            </td>
                        </tr>
                         
                            <td><input type="hidden" name="secondStudentId" id="secondStudentId"></td>
                         
                        <tr>
                            <td></td>
                            <td>
                                <input class="btn btn-success" type="submit" value="Submit" name="second" id="">
                            </td>
                        </tr>
                    </table>
                     
                </form>
            </div>
             
        </div>
    </div>
</div>

<!-- second --> 

<!-- third -->

<div class="modal fade" id="thirdModal" tabindex="-1" aria-labelledby="imageModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-header">
           
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body text-center">
                
                <form method="POST">
                    {% csrf_token %}
                    <table style="border-collapse: separate;border-spacing: 10px;">
                        <tr>
                            <td>
                                <label for="admission_no" style="font-size: 20px;font-weight: bold;" class="form-label text-dark py-2">Select</label>
                            </td>
                            <td>
                                <select name="thirdLanguage" style="font-size: 18px;font-weight: bold;" id="" class="form-control">
                                     
                                    <option value="malayalam">Malayalam</option>
                                    <option value="urdu1">URDU 1</option>
                                  
                                </select>
                            </td>
                        </tr>
                         
                            <td><input type="text" name="thirdStudentId" id="thirdStudentId"></td>
                         
                        <tr>
                            <td></td>
                            <td>
                                <input class="btn btn-success" type="submit" value="Submit" name="third" id="">
                            </td>
                        </tr>
                    </table>
                     
                </form>
            </div>
             
        </div>
    </div>
</div>

<!-- third --> 

    


    <script>
        // JavaScript to load the image into the modal
        document.addEventListener('DOMContentLoaded', function () {
            const imageLinks = document.querySelectorAll('.view-pic');
            
            imageLinks.forEach(link => {
                link.addEventListener('click', function () {
                    const imageUrl = this.getAttribute('data-image-url');
                    const modalImage = document.getElementById('modalImage');
                    
                    // Set the image source to the clicked image URL
                    modalImage.src = imageUrl;
                });
            });
        });
        </script>


<script>
   
   function getStudentId(id, subject){
    console.log(subject,id)
    if(subject == 'moral'){
    document.getElementById('moralStudentId').value = id

    }
    else if(subject == 'second'){
         console.log(id,'--')
    document.getElementById('secondStudentId').value = id

    }
    else if(subject == 'third'){
    document.getElementById('thirdStudentId').value = id

    }
   }
    </script>
    
    {% endblock %}


 

school_app/school_teacher/templates/teacher/upload_notes.html
{% extends "teacher/master.html" %}

{% block content %}
<div class="container d-flex justify-content-center " style="min-height: 100vh;">
    <div class="col-md-6">
        <div class="card-body">
            <h3 class="text-center py-3" style="font-weight: bolder;">Add Notes</h3>
             
            {% if message %}
           <div class="alert  mt-3"  style="background-color: #EE4266;color: white;" id="error-msg" role="alert">
            {{ message }}
          </div>
          {% endif %}
            <form method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="mb-1">
                    <label for="roll_no" class="form-label text-dark py-2">Select Class</label>
                    <select name="cls" required class="form-control" id="">
                        <option value="1">1</option>
                        <option value="2">2</option>
                        <option value="3">3</option>
                        <option value="4">4</option>
                        <option value="5">5</option>
                        <option value="6">6</option>
                        <option value="7">7</option>
                        <option value="8">8</option>
                        <option value="9">9</option>
                        <option value="10">10</option>

                    </select>
                </div>

                <div class="mb-1">
                    <label for="roll_no" class="form-label text-dark py-2">Subject</label>
                    <select name="sub" required class="form-control" id="">
                        <option value="maths">Maths</option>
                        <option value="english">English</option>
                        <option value="science">Science</option>

                        <option value="computer">Computer</option>
                         
                    </select>
                </div>
                 
                
                <div class="mb-1">
                    <label for="studentName" class="form-label text-dark py-2">Description</label>
                    <textarea   class="form-control" name="descr" id=""></textarea>
                </div>    
                <div class="mb-1">
                    <label for="studentName" class="form-label text-dark py-2">Description</label>
                    <input type="file"   class="form-control" name="file" id=""> 
                </div>    
                 
                 
                <div>
                <button type="submit" class="btn btn-primary d-flex justify-content-center w-100">Add Now</button>

                </div>
            </form>

            
        </div>
    </div>
 
 

    <script>
        setTimeout(function() {
           var errorMsg = document.getElementById('error-msg');
           if (errorMsg) {
              errorMsg.style.display = 'none';
           }
        }, 2000); // 5000 milliseconds = 5 seconds
     </script>
</div>
{% endblock %}
 