school_app/school_app/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
    
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('school_student.urls')),
    path('school/admin/',include('school_admin.urls')),
    path('school/teacher/',include('school_teacher.urls'))

]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

school_app/school_student/urls.py
from django.urls import path
from . import views

app_name = 'student'
urlpatterns = [
    path('', views.admin_login, name = 'admin_login'),
    path('student/home', views.home, name = 'home'),
    path('notes/list', views.notes, name = 'notes'),

    path('teacher/login', views.teacher_login, name = 'teacher_login'),
    path('student/login', views.student_login, name = 'student_login'),
    
]

school_app/school_student/models.py
from django.db import models
import datetime

# Create your models here.
class Notes(models.Model):
    subject = models.CharField()
    date = models.DateField(default=datetime.date.today)
    description = models.CharField(max_length = 200)
    added_by = models.CharField(max_length=100)
    student_cls = models.IntegerField()
    file = models.FileField(upload_to="notes/")
     
    status = models.CharField(max_length=20, default = 'active')
    class Meta:
        db_table = "notes"

school_app/school_student/views.py
from django.shortcuts import render,redirect
from school_admin.models import *
from school_teacher.models import *
from .models import *

def admin_login(request):
    message = ''
    if request.method == 'POST':
        admin_id = request.POST['admin_id']
        password = request.POST['password']

        record = SchoolAdmin.objects.filter(admin_id = admin_id, password = password)
        if record:
            request.session['admin_id'] = record[0].admin_id
            return redirect('hm:hm_dashboard')
        else:
            message = 'User Name or Password Incorrect'
    return render(request,'school_student/admin_login.html', {'message': message})


def teacher_login(request):
    message = ''
    if request.method == 'POST':
        teacher_id = request.POST['teacher_id']
        password = request.POST['password']

        record = Teacher.objects.filter(teacher_id = teacher_id, password = password)

        if record:
            request.session['teacher_id'] = record[0].id
            request.session['teacher_name'] = record[0].teacher_name
            request.session['teacher_class'] = record[0].teacher_class
            request.session['division'] = record[0].division

            
            print('hhh')
            return redirect('teacher:home')

        else:
            print('here')
            message = 'User Name or Password Incorrect'
    return render(request,'school_student/teacher_login.html', {'message': message})

def student_login(request):
    message = ''
    if request.method == 'POST':
        student_id = request.POST['admission_id']
        password = request.POST['password']
    
        record = Student.objects.filter(admission_no = student_id, password = password)
        if record:
            request.session['student_id'] = record[0].id
            request.session['student_name'] = record[0].student_name
            request.session['student_class'] = record[0].student_class
            request.session['division'] = record[0].division
            return redirect('student:home')
        else:
            message = 'User Name or Password Incorrect'
    return render(request,'school_student/student_login.html', {'message': message})


def home(request):
    return render(request,'school_student/home.html')

def notes(request):
    notes = Notes.objects.filter(student_cls = request.session['student_class'])
    return render(request,'school_student/view_notes.html',{'notes': notes})

school_app/school_student/templates/school_student/admin_login.html
{% load static %}
<html lang="en">

  <head>

    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@100;200;300;400;500;600;700;800;900&display=swap" rel="stylesheet">

    <title>ERP</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">


    <!-- Additional CSS Files -->
    <link rel="stylesheet" href="{% static 'assets/css/fontawesome.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/templatemo-digimedia-v1.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/animated.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/owl.css' %}">
<!--

TemplateMo 568 DigiMedia

https://templatemo.com/tm-568-digimedia

-->
  </head>

<body>

  <!-- ***** Preloader Start ***** -->
  <div id="js-preloader" class="js-preloader">
    <div class="preloader-inner">
      <span class="dot"></span>
      <div class="dots">
        <span></span>
        <span></span>
        <span></span>
      </div>
    </div>
  </div>
  <!-- ***** Preloader End ***** -->

  <!-- Pre-header Starts -->
  <div class="pre-header">
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-sm-8 col-7">
          <ul class="info">
            <li><a href="#"><i class="fa fa-envelope"></i>alif@admin.com</a></li>
            <li><a href="#"><i class="fa fa-phone"></i>+966 6544251</a></li>
          </ul>
        </div>
         
      </div>
    </div>
  </div>
  <!-- Pre-header End -->

  <!-- ***** Header Area Start ***** -->
  <header class="header-area header-sticky wow slideInDown" data-wow-duration="0.75s" data-wow-delay="0s">
    <div class="container">
      <div class="row">
        <div class="col-12">
          <nav class="main-nav">
            <!-- ***** Logo Start ***** -->
            <a href="index.html" class="logo">
              <img src="{% static 'assets/images/logo-v1.png' %}" alt="">
            </a>
            <!-- ***** Logo End ***** -->
            <!-- ***** Menu Start ***** -->
            <ul class="nav">
                <li class="scroll-to-section"><a href="{% url 'student:admin_login' %}" class="active">Home</a></li>
                 
                <li class="scroll-to-section"><a href="{% url 'student:teacher_login' %}" class="active">Teacher Login</a></li> 
                <li class="scroll-to-section"><div class="border-first-button" ><a href="{% url 'student:student_login' %}" > Student Login</a></div></li> 
              </ul>       
            <a class='menu-trigger'>
                <span>Menu</span>
            </a>
            <!-- ***** Menu End ***** -->
          </nav>
        </div>
      </div>
    </div>
  </header>
  <!-- ***** Header Area End ***** -->

   

  <div id="about" class="about section">
    <div class="container">
      <div class="row">
        <div class="col-lg-12">
          <div class="row">
            <div class="col-lg-6">
              <div class="about-left-image  wow fadeInLeft" data-wow-duration="1s" data-wow-delay="0.5s">
                <img src="{% static 'assets/images/about-dec.png' %}" alt="">
              </div>
            </div>
            <div class="col-lg-6 align-self-center  wow fadeInRight" data-wow-duration="1s" data-wow-delay="0.5s">
                <div>
                    <h3>Admin Login</h3>
                </div>
                <form method="POST">
               
              <div class="mb-4  ">
                <label for="adminId" class="form-label text-dark py-2" >Email address</label>
                <input type="text" class="form-control " required  id="hm_id" name="hm_id" placeholder="Enter your ID">
              </div>
              <div class="mb-4">
                <label for="password" class="form-label text-dark py-2">Password</label>
                <input type="password" class="form-control" required name="password"  id="password" placeholder="Enter your password">
              </div>
               
              <button type="submit" class="btn btn-primary"  >Login</button>
              
            </form>

            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

   
  
   


   
  
   

   
  <footer>
    <div class="container">
      <div class="row">
        <div class="col-lg-12">
          <p>Copyright © 2022 DigiMedia Co., Ltd. All Rights Reserved. 
          <br>Design: <a href="https://templatemo.com" target="_parent" title="free css templates">TemplateMo</a></p>
        </div>
      </div>
    </div>
  </footer>


  <!-- Scripts -->
  <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
  <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
  <script src="{% static 'assets/js/owl-carousel.js' %}"></script>
  <script src="{% static 'assets/js/animation.js' %}"></script>
  <script src="{% static 'assets/js/imagesloaded.js' %}"></script>
  <script src="{% static 'assets/js/custom.js' %}"></script>

</body>
</html>

school_app/school_student/templates/school_student/home.html
{% extends "school_student/master.html" %}

{% block content %}
    <h3 style="font-size: 40px; margin-top: 170px;  margin-left: 300px;">Welcome {{request.session.student_name | title}}</h3>
{% endblock %}
 

school_app/school_student/templates/school_student/master.html
{% load static %}
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>ERP</title>
    <!-- plugins:css -->
    <link rel="stylesheet" href="{% static 'scl_admin/assets/vendors/feather/feather.css' %}">
    <link rel="stylesheet" href="{% static 'scl_admin/assets/vendors/ti-icons/css/themify-icons.css' %}">
    <link rel="stylesheet" href="{% static 'scl_admin/assets/vendors/css/vendor.bundle.base.css' %}">
    <link rel="stylesheet" href="{% static 'scl_admin/assets/vendors/font-awesome/css/font-awesome.min.css' %}">
    <link rel="stylesheet" href="{% static 'scl_admin/assets/vendors/mdi/css/materialdesignicons.min.css' %}">
    <!-- endinject -->
    <!-- Plugin css for this page -->
    <!-- <link rel="stylesheet" href="assets/vendors/datatables.net-bs4/dataTables.bootstrap4.css"> -->
    <link rel="stylesheet" href="{% static 'scl_admin/assets/vendors/datatables.net-bs5/dataTables.bootstrap5.css' %}">
    <link rel="stylesheet" href="{% static 'scl_admin/assets/vendors/ti-icons/css/themify-icons.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'scl_admin/assets/js/select.dataTables.min.css' %}">
    <!-- End plugin css for this page -->
    <!-- inject:css -->
    <link rel="stylesheet" href="{% static 'scl_admin/assets/css/style.css' %}">
    <!-- endinject -->
    <link rel="shortcut icon" href="{% static 'scl_admin/assets/images/favicon.png' %}" />
  </head>
  <body>
     
      <!-- partial:partials/_navbar.html -->
      <nav class="navbar col-lg-12 col-12 p-0 fixed-top d-flex flex-row">
  <div class="text-center navbar-brand-wrapper d-flex align-items-center justify-content-start">
    <a class="navbar-brand brand-logo me-5" href="index.html"><img src="{% static 'scl_admin/assets/images/logo.svg' %}" class="me-2" alt="logo" /></a>
    <a class="navbar-brand brand-logo-mini" href="index.html"><img src="{% static 'scl_admin/assets/images/logo-mini.svg' %}" alt="logo" /></a>
  </div>
  <div class="navbar-menu-wrapper d-flex align-items-center justify-content-end">
    <button class="navbar-toggler navbar-toggler align-self-center" type="button" data-toggle="minimize">
      <span class="icon-menu"></span>
    </button>
    <ul class="navbar-nav mr-lg-2">
      <li class="nav-item nav-search d-none d-lg-block">
        <div class="input-group">
          <div class="input-group-prepend hover-cursor" id="navbar-search-icon">
            <span class="input-group-text" id="search">
              <i class="icon-search"></i>
            </span>
          </div>
          <input type="text" class="form-control" id="navbar-search-input" placeholder="Search now" aria-label="search" aria-describedby="search">
        </div>
      </li>
    </ul>
    <ul class="navbar-nav navbar-nav-right">
       
       
      <li class="nav-item nav-profile dropdown">
        <a class="nav-link dropdown-toggle" href="#" data-bs-toggle="dropdown" id="profileDropdown">
          <img src="{% static 'scl_admin/assets/images/faces/face28.jpg' %}" alt="profile" />
        </a>
        <div class="dropdown-menu dropdown-menu-right navbar-dropdown" aria-labelledby="profileDropdown">
           
          <a class="dropdown-item">
            <i class="ti-power-off text-primary"></i> Logout </a>
        </div>
      </li>
      <li class="nav-item nav-settings d-none d-lg-flex">
        <a class="nav-link" href="#">
          <i class="icon-ellipsis"></i>
        </a>
      </li>
    </ul>
    <button class="navbar-toggler navbar-toggler-right d-lg-none align-self-center" type="button" data-toggle="offcanvas">
      <span class="icon-menu"></span>
    </button>
  </div>
</nav>
      <!-- partial -->
      <div class="container-fluid page-body-wrapper">
        <!-- partial:partials/_sidebar.html -->
        <nav class="sidebar sidebar-offcanvas" id="sidebar">
  <ul class="nav">
    <li class="nav-item">
      <a class="nav-link" href="{% url 'student:home' %}">
        <i class="icon-grid menu-icon"></i>
        <span class="menu-title">Dashboard</span>
      </a>
    </li>
    <li class="nav-item">
      <a class="nav-link"   href="{% url 'student:notes' %}"  >
        <i class="icon-layout menu-icon"></i>
        <span class="menu-title">View Notes</span>
        <i class="menu-arrow"></i>
      </a>
       
    </li>
    <li class="nav-item">
        <a class="nav-link"   href=" "  >
          <i class="icon-layout menu-icon"></i>
          <span class="menu-title">Anouncements</span>
          <i class="menu-arrow"></i>
        </a>
         
      </li>
     
    <li class="nav-item">
      <a class="nav-link" href="../../../docs/documentation.html">
        <i class="icon-paper menu-icon"></i>
        <span class="menu-title">Logout </span>
      </a>
    </li>
  </ul>
</nav>
        <!-- partial -->
        <div class="main-panel">
          <div class="content-wrapper">
            
              
            {% block content %}

            {% endblock %}
             
             
             
             
          </div>
          
        </div>
        <!-- main-panel ends -->
      </div>
      <!-- page-body-wrapper ends -->
    </div>
    <!-- container-scroller -->
    <!-- plugins:js -->
    <script src="{% static 'scl_admin/assets/vendors/js/vendor.bundle.base.js' %}"></script>
    <!-- endinject -->
    <!-- Plugin js for this page -->
    <script src="{% static 'scl_admin/assets/vendors/chart.js/chart.umd.js' %}"></script>
    <script src="{% static 'scl_admin/assets/vendors/datatables.net/jquery.dataTables.js' %}"></script>
    <!-- <script src="{% static 'scl_admin/assets/vendors/datatables.net-bs4/dataTables.bootstrap4.js"></script> -->
    <script src="{% static 'scl_admin/assets/vendors/datatables.net-bs5/dataTables.bootstrap5.js' %}"></script>
    <script src="{% static 'scl_admin/assets/js/dataTables.select.min.js' %}"></script>
    <!-- End plugin js for this page -->
    <!-- inject:js -->
    <script src="{% static 'scl_admin/assets/js/off-canvas.js' %}"></script>
    <script src="{% static 'scl_admin/assets/js/template.js' %}"></script>
    <script src="{% static 'scl_admin/assets/js/settings.js' %}"></script>
    <script src="{% static 'scl_admin/assets/js/todolist.js' %}"></script>
    <!-- endinject -->
    <!-- Custom js for this page-->
    <script src="{% static 'scl_admin/assets/js/jquery.cookie.js' %}" type="text/javascript"></script>
    <script src="{% static 'scl_admin/assets/js/dashboard.js' %}"></script>
    <!-- <script src="assets/js/Chart.roundedBarCharts.js"></script> -->
    <!-- End custom js for this page-->
  </body>
</html>

school_app/school_student/templates/school_student/student_login.html
{% load static %}
<html lang="en">

  <head>

    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@100;200;300;400;500;600;700;800;900&display=swap" rel="stylesheet">

    <title>ERP</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">


    <!-- Additional CSS Files -->
    <link rel="stylesheet" href="{% static 'assets/css/fontawesome.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/templatemo-digimedia-v1.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/animated.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/owl.css' %}">
<!--

TemplateMo 568 DigiMedia

https://templatemo.com/tm-568-digimedia

-->
  </head>

<body>

  <!-- ***** Preloader Start ***** -->
  <div id="js-preloader" class="js-preloader">
    <div class="preloader-inner">
      <span class="dot"></span>
      <div class="dots">
        <span></span>
        <span></span>
        <span></span>
      </div>
    </div>
  </div>
  <!-- ***** Preloader End ***** -->

  <!-- Pre-header Starts -->
  <div class="pre-header">
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-sm-8 col-7">
          <ul class="info">
            <li><a href="#"><i class="fa fa-envelope"></i>alif@admin.com</a></li>
            <li><a href="#"><i class="fa fa-phone"></i>+966 6544251</a></li>
          </ul>
        </div>
         
      </div>
    </div>
  </div>
  <!-- Pre-header End -->

  <!-- ***** Header Area Start ***** -->
  <header class="header-area header-sticky wow slideInDown" data-wow-duration="0.75s" data-wow-delay="0s">
    <div class="container">
      <div class="row">
        <div class="col-12">
          <nav class="main-nav">
            <!-- ***** Logo Start ***** -->
            <a href="index.html" class="logo">
              <img src="{% static 'assets/images/logo-v1.png' %}" alt="">
            </a>
            <!-- ***** Logo End ***** -->
            <!-- ***** Menu Start ***** -->
            <ul class="nav">
                <li class="scroll-to-section"><a href="{% url 'student:admin_login' %}" class="active">Home</a></li>
                 
                <li class="scroll-to-section"><a href="{% url 'student:teacher_login' %}" class="active">Teacher Login</a></li> 
                <li class="scroll-to-section"><div class="border-first-button" ><a href="{% url 'student:student_login' %}" > Student Login</a></div></li> 
              </ul>         
            <a class='menu-trigger'>
                <span>Menu</span>
            </a>
            <!-- ***** Menu End ***** -->
          </nav>
        </div>
      </div>
    </div>
  </header>
  <!-- ***** Header Area End ***** -->

   

  <div id="about" class="about section">
    <div class="container">
      <div class="row">
        <div class="col-lg-12">
          <div class="row">
            <div class="col-lg-6">
              <div class="about-left-image  wow fadeInLeft" data-wow-duration="1s" data-wow-delay="0.5s">
                <img src="{% static 'assets/images/about-dec.png' %}" alt="">
              </div>
            </div>
            <div class="col-lg-6 align-self-center  wow fadeInRight" data-wow-duration="1s" data-wow-delay="0.5s">
                <div>
                    <h3>Student Login</h3>
                </div>
                {% if message %}
                <div class="alert  mt-3"  style="background-color: #EE4266;color: white;" id="error-msg" role="alert">
                 {{ message }}
               </div>
               {% endif %}
                <form method="POST">
               {% csrf_token %}
              <div class="mb-4  ">
                <label for="adminId" class="form-label text-dark py-2" >Admission No</label>
                <input type="number" class="form-control " required  id="hm_id" name="admission_id" placeholder="Enter your ID">
              </div>
              <div class="mb-4">
                <label for="password" class="form-label text-dark py-2">Password</label>
                <input type="password" class="form-control" required name="password"  id="password" placeholder="Enter your password">
              </div>
               
              <button type="submit" class="btn btn-primary"  >Login</button>
              
            </form>

            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

   
  <script>
    setTimeout(function() {
       var errorMsg = document.getElementById('error-msg');
       if (errorMsg) {
          errorMsg.style.display = 'none';
       }
    }, 2000); // 5000 milliseconds = 5 seconds
 </script>
   


   
  
   

   
  <footer>
    <div class="container">
      <div class="row">
        <div class="col-lg-12">
          <p>Copyright © 2022 DigiMedia Co., Ltd. All Rights Reserved. 
          <br>Design: <a href="https://templatemo.com" target="_parent" title="free css templates">TemplateMo</a></p>
        </div>
      </div>
    </div>
  </footer>


  <!-- Scripts -->
  <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
  <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
  <script src="{% static 'assets/js/owl-carousel.js' %}"></script>
  <script src="{% static 'assets/js/animation.js' %}"></script>
  <script src="{% static 'assets/js/imagesloaded.js' %}"></script>
  <script src="{% static 'assets/js/custom.js' %}"></script>

</body>
</html>

school_app/school_student/templates/school_student/teacher_login.html
{% load static %}
<html lang="en">

  <head>

    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@100;200;300;400;500;600;700;800;900&display=swap" rel="stylesheet">

    <title>ERP</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">


    <!-- Additional CSS Files -->
    <link rel="stylesheet" href="{% static 'assets/css/fontawesome.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/templatemo-digimedia-v1.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/animated.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/owl.css' %}">
<!--

TemplateMo 568 DigiMedia

https://templatemo.com/tm-568-digimedia

-->
  </head>

<body>

  <!-- ***** Preloader Start ***** -->
  <div id="js-preloader" class="js-preloader">
    <div class="preloader-inner">
      <span class="dot"></span>
      <div class="dots">
        <span></span>
        <span></span>
        <span></span>
      </div>
    </div>
  </div>
  <!-- ***** Preloader End ***** -->

  <!-- Pre-header Starts -->
  <div class="pre-header">
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-sm-8 col-7">
          <ul class="info">
            <li><a href="#"><i class="fa fa-envelope"></i>alif@admin.com</a></li>
            <li><a href="#"><i class="fa fa-phone"></i>+966 6544251</a></li>
          </ul>
        </div>
         
      </div>
    </div>
  </div>
  <!-- Pre-header End -->

  <!-- ***** Header Area Start ***** -->
  <header class="header-area header-sticky wow slideInDown" data-wow-duration="0.75s" data-wow-delay="0s">
    <div class="container">
      <div class="row">
        <div class="col-12">
          <nav class="main-nav">
            <!-- ***** Logo Start ***** -->
            <a href="index.html" class="logo">
              <img src="{% static 'assets/images/logo-v1.png' %}" alt="">
            </a>
            <!-- ***** Logo End ***** -->
            <!-- ***** Menu Start ***** -->
            <ul class="nav">
                <li class="scroll-to-section"><a href="{% url 'student:admin_login' %}" class="active">Home</a></li>
                 
                <li class="scroll-to-section"><a href="{% url 'student:teacher_login' %}" class="active">Teacher Login</a></li> 
                <li class="scroll-to-section"><div class="border-first-button" ><a href="{% url 'student:student_login' %}" > Student Login</a></div></li> 
              </ul>       
            <a class='menu-trigger'>
                <span>Menu</span>
            </a>
            <!-- ***** Menu End ***** -->
          </nav>
        </div>
      </div>
    </div>
  </header>
  <!-- ***** Header Area End ***** -->

   

  <div id="about" class="about section">
    <div class="container">
      <div class="row">
        <div class="col-lg-12">
          <div class="row">
            <div class="col-lg-6">
              <div class="about-left-image  wow fadeInLeft" data-wow-duration="1s" data-wow-delay="0.5s">
                <img src="{% static 'assets/images/about-dec.png' %}" alt="">
              </div>
            </div>
            <div class="col-lg-6 align-self-center  wow fadeInRight" data-wow-duration="1s" data-wow-delay="0.5s">
                <div>
                    <h3>Teacher Login</h3>
                </div>
                <form method="POST">
                    {% csrf_token %}
                    {% if message %}
                    <div class="alert alert-primary mt-3" id="error-msg" role="alert">
                     {{ message }}
                   </div>
                   {% endif %}
                      
              <div class="mb-4  ">

                <label for="adminId" class="form-label text-dark py-2" >Staff ID</label>
                <input type="number" class="form-control " required  id="teacher_id" name="teacher_id" placeholder="Enter your ID">
              </div>
              <div class="mb-4">
                <label for="password" class="form-label text-dark py-2">Password</label>
                <input type="password" class="form-control" required name="password"  id="password" placeholder="Enter your password">
              </div>
               
              <button type="submit" class="btn btn-primary"  >Login</button>
              
            </form>

            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

   
  
   


   
  
   

   
  <footer>
    <div class="container">
      <div class="row">
        <div class="col-lg-12">
          <p>Copyright © 2022 DigiMedia Co., Ltd. All Rights Reserved. 
          <br>Design: <a href="https://templatemo.com" target="_parent" title="free css templates">TemplateMo</a></p>
        </div>
      </div>
    </div>
  </footer>


  <!-- Scripts -->
  <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
  <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
  <script src="{% static 'assets/js/owl-carousel.js' %}"></script>
  <script src="{% static 'assets/js/animation.js' %}"></script>
  <script src="{% static 'assets/js/imagesloaded.js' %}"></script>
  <script src="{% static 'assets/js/custom.js' %}"></script>

</body>
</html>

<script>
    setTimeout(function() {
       var errorMsg = document.getElementById('error-msg');
       if (errorMsg) {
          errorMsg.style.display = 'none';
       }
    }, 2000); // 5000 milliseconds = 5 seconds
 </script>  