school_app/school_admin/urls.py
from django.urls import path
from . import views

app_name = 'school_admin'
urlpatterns = [
    path('', views.home, name = 'home'),   
    path('teacher/add', views.add_teacher, name = 'add_teacher'),   
    path('teachers/list', views.teachers_list, name = 'teachers_list')
     

]

school_app/school_app/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
    
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('school_student.urls')),
    path('school/admin/',include('school_admin.urls')),
    path('school/teacher/',include('school_teacher.urls'))

]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

school_app/school_admin/models.py
from django.db import models

# Create your models here.
class SchoolAdmin(models.Model):
    admin_id = models.CharField(max_length = 50)
    password = models.CharField(max_length = 30)
     
    class Meta:
        db_table = "school_admin"

school_app/school_admin/views.py
from django.shortcuts import render
from school_teacher.models import Teacher 

def home(request):
    return render(request,'school_admin/home.html')

def add_teacher(request):
    message = ''
    if request.method == 'POST':
        teacher_id = request.POST['teacherId']
        teacher_name = request.POST['teacherName'].lower()
        cls = request.POST['cls']
        division = request.POST['division']
        section = request.POST['section']


        record = Teacher.objects.filter(teacher_id = teacher_id)

        if not record:
            _ = Teacher(teacher_id=teacher_id, teacher_name=teacher_name,
                         teacher_class=cls,
                         division=division,
                         password='alif@12345',
                         section = section,
                          
                         ).save()
            message = 'Teacher Added Succesfully '

        else:
            message = 'Teacher ID Exist'
    return render(request,'school_admin/add_teacher.html',{'message': message})

def teachers_list(request):
    if request.method == 'POST':
        if 'flt_class' in request.POST:
            print('hello')
        if 'flt_division' in request.POST:
            print('divisionnn')
        if 'flt_section' in request.POST:
            print('section')
    teachers_list = Teacher.objects.filter(staff_status = 'active')
    return render(request, 'school_admin/teachers_list.html',{'teachers_list': teachers_list})

school_app/school_admin/templates/school_admin/add_teacher.html
{% extends "school_admin/master.html" %}

{% block content %}
<div class="container d-flex justify-content-center " style="min-height: 100vh;">
    <div class="col-md-6">
        <div class="card-body">
            <h3 class="text-center py-3" style="font-weight: bolder;">Add Teacher</h3>
             
            {% if message %}
           <div class="alert  mt-3"  style="background-color: #EE4266;color: white;" id="error-msg" role="alert">
            {{ message }}
          </div>
          {% endif %}
            <form method="POST">
                {% csrf_token %}
                <div class="mb-1">
                    <label for="teacher_id" class="form-label text-dark py-2">Teacher ID</label>
                    <input type="number"class="form-control" name="teacherId" id="">
                </div>
                <div class="mb-1">
                    <label for="teacherName" class="form-label text-dark py-2">Teacher Name</label>
                    <input type="text" class="form-control" name="teacherName" id="">
                </div>
                <div class="mb-1">
                    <label for="class" class="form-label text-dark py-2">Class</label>
                    <select name="cls" required class="form-control" id="">
                        <option value="1">1</option>
                        <option value="2">2</option>
                        <option value="3">3</option>
                        <option value="4">4</option>
                        <option value="5">5</option>
                        <option value="6">6</option>
                        <option value="7">7</option>
                        <option value="8">8</option>
                        <option value="9">9</option>
                        <option value="10">10</option>

                    </select>
                </div>
                <div class="mb-1">
                    <label for="division" class="form-label text-dark py-2">Division</label>
                    <select name="division" required class="form-control" id="">
                        <option value="a">A</option>
                        <option value="b">B</option>
                        <option value="c">C</option>
                        <option value="d">D</option>
                        <option value="e">E</option>
                        <option value="f">F</option>
                        <option value="g">G</option>
                        <option value="h">H</option>
                        <option value="i">I</option>
                        <option value="j">J</option>
                    </select>
                </div>
                <div class="mb-1">
                    <label for="section" class="form-label text-dark py-2">Section</label>
                    <select name="section" required class="form-control" id="">
                        <option value="g">Girls</option>
                        <option value="b">Boys</option>
                    </select>
                </div>
                 
                 
                 
                <div>
                <button type="submit" class="btn btn-primary d-flex justify-content-center w-100">Add Now</button>

                </div>
            </form>

            
        </div>
    </div>
 
 

    <script>
        setTimeout(function() {
           var errorMsg = document.getElementById('error-msg');
           if (errorMsg) {
              errorMsg.style.display = 'none';
           }
        }, 2000); // 5000 milliseconds = 5 seconds
     </script>
</div>
{% endblock %}
 

school_app/school_admin/templates/school_admin/home.html
{% extends "school_admin/master.html" %}

{% block content %}
    <h3 style="font-size: 40px; margin-top: 170px;  margin-left: 300px;">Welcome Admin</h3>
{% endblock %}
 

school_app/school_admin/templates/school_admin/master.html
{% load static %}
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>ERP</title>
    <!-- plugins:css -->
    <link rel="stylesheet" href="{% static 'scl_admin/assets/vendors/feather/feather.css' %}">
    <link rel="stylesheet" href="{% static 'scl_admin/assets/vendors/ti-icons/css/themify-icons.css' %}">
    <link rel="stylesheet" href="{% static 'scl_admin/assets/vendors/css/vendor.bundle.base.css' %}">
    <link rel="stylesheet" href="{% static 'scl_admin/assets/vendors/font-awesome/css/font-awesome.min.css' %}">
    <link rel="stylesheet" href="{% static 'scl_admin/assets/vendors/mdi/css/materialdesignicons.min.css' %}">
    <!-- endinject -->
    <!-- Plugin css for this page -->
    <!-- <link rel="stylesheet" href="assets/vendors/datatables.net-bs4/dataTables.bootstrap4.css"> -->
    <link rel="stylesheet" href="{% static 'scl_admin/assets/vendors/datatables.net-bs5/dataTables.bootstrap5.css' %}">
    <link rel="stylesheet" href="{% static 'scl_admin/assets/vendors/ti-icons/css/themify-icons.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'scl_admin/assets/js/select.dataTables.min.css' %}">
    <!-- End plugin css for this page -->
    <!-- inject:css -->
    <link rel="stylesheet" href="{% static 'scl_admin/assets/css/style.css' %}">
    <!-- endinject -->
    <link rel="shortcut icon" href="{% static 'scl_admin/assets/images/favicon.png' %}" />
  </head>
  <body>
     
      <!-- partial:partials/_navbar.html -->
      <nav class="navbar col-lg-12 col-12 p-0 fixed-top d-flex flex-row">
  <div class="text-center navbar-brand-wrapper d-flex align-items-center justify-content-start">
    <a class="navbar-brand brand-logo me-5" href="index.html"><img src="{% static 'scl_admin/assets/images/logo.svg' %}" class="me-2" alt="logo" /></a>
    <a class="navbar-brand brand-logo-mini" href="index.html"><img src="{% static 'scl_admin/assets/images/logo-mini.svg' %}" alt="logo" /></a>
  </div>
  <div class="navbar-menu-wrapper d-flex align-items-center justify-content-end">
    <button class="navbar-toggler navbar-toggler align-self-center" type="button" data-toggle="minimize">
      <span class="icon-menu"></span>
    </button>
    <ul class="navbar-nav mr-lg-2">
      <li class="nav-item nav-search d-none d-lg-block">
        <div class="input-group">
          <div class="input-group-prepend hover-cursor" id="navbar-search-icon">
            <span class="input-group-text" id="search">
              <i class="icon-search"></i>
            </span>
          </div>
          <input type="text" class="form-control" id="navbar-search-input" placeholder="Search now" aria-label="search" aria-describedby="search">
        </div>
      </li>
    </ul>
    <ul class="navbar-nav navbar-nav-right">
       
       
      <li class="nav-item nav-profile dropdown">
        <a class="nav-link dropdown-toggle" href="#" data-bs-toggle="dropdown" id="profileDropdown">
          <img src="{% static 'scl_admin/assets/images/faces/face28.jpg' %}" alt="profile" />
        </a>
        <div class="dropdown-menu dropdown-menu-right navbar-dropdown" aria-labelledby="profileDropdown">
           
          <a class="dropdown-item">
            <i class="ti-power-off text-primary"></i> Logout </a>
        </div>
      </li>
      <li class="nav-item nav-settings d-none d-lg-flex">
        <a class="nav-link" href="#">
          <i class="icon-ellipsis"></i>
        </a>
      </li>
    </ul>
    <button class="navbar-toggler navbar-toggler-right d-lg-none align-self-center" type="button" data-toggle="offcanvas">
      <span class="icon-menu"></span>
    </button>
  </div>
</nav>
      <!-- partial -->
      <div class="container-fluid page-body-wrapper">
        <!-- partial:partials/_sidebar.html -->
        <nav class="sidebar sidebar-offcanvas" id="sidebar">
  <ul class="nav">
    <li class="nav-item">
      <a class="nav-link" href="index.html">
        <i class="icon-grid menu-icon"></i>
        <span class="menu-title">Dashboard</span>
      </a>
    </li>
    <li class="nav-item">
      <a class="nav-link"   href="{% url 'school_admin:add_teacher' %}"  >
        <i class="icon-layout menu-icon"></i>
        <span class="menu-title">Add Teachers</span>
        <i class="menu-arrow"></i>
      </a>
       
    </li>
    <li class="nav-item">
        <a class="nav-link"   href="{% url 'school_admin:teachers_list' %}"  >
          <i class="icon-layout menu-icon"></i>
          <span class="menu-title">Teachers List</span>
          <i class="menu-arrow"></i>
        </a>
         
      </li>
     
    <li class="nav-item">
      <a class="nav-link" href="../../../docs/documentation.html">
        <i class="icon-paper menu-icon"></i>
        <span class="menu-title">Logout </span>
      </a>
    </li>
  </ul>
</nav>
        <!-- partial -->
        <div class="main-panel">
          <div class="content-wrapper">
            
              
            {% block content %}

            {% endblock %}
             
             
             
             
          </div>
          
        </div>
        <!-- main-panel ends -->
      </div>
      <!-- page-body-wrapper ends -->
    </div>
    <!-- container-scroller -->
    <!-- plugins:js -->
    <script src="{% static 'scl_admin/assets/vendors/js/vendor.bundle.base.js' %}"></script>
    <!-- endinject -->
    <!-- Plugin js for this page -->
    <script src="{% static 'scl_admin/assets/vendors/chart.js/chart.umd.js' %}"></script>
    <script src="{% static 'scl_admin/assets/vendors/datatables.net/jquery.dataTables.js' %}"></script>
    <!-- <script src="{% static 'scl_admin/assets/vendors/datatables.net-bs4/dataTables.bootstrap4.js"></script> -->
    <script src="{% static 'scl_admin/assets/vendors/datatables.net-bs5/dataTables.bootstrap5.js' %}"></script>
    <script src="{% static 'scl_admin/assets/js/dataTables.select.min.js' %}"></script>
    <!-- End plugin js for this page -->
    <!-- inject:js -->
    <script src="{% static 'scl_admin/assets/js/off-canvas.js' %}"></script>
    <script src="{% static 'scl_admin/assets/js/template.js' %}"></script>
    <script src="{% static 'scl_admin/assets/js/settings.js' %}"></script>
    <script src="{% static 'scl_admin/assets/js/todolist.js' %}"></script>
    <!-- endinject -->
    <!-- Custom js for this page-->
    <script src="{% static 'scl_admin/assets/js/jquery.cookie.js' %}" type="text/javascript"></script>
    <script src="{% static 'scl_admin/assets/js/dashboard.js' %}"></script>
    <!-- <script src="assets/js/Chart.roundedBarCharts.js"></script> -->
    <!-- End custom js for this page-->
  </body>
</html>

school_app/school_admin/templates/school_admin/teachers_list.html
{% extends 'school_admin/master.html' %}

{% block content %}
<div class="container d-flex justify-content-center " style="min-height: 100vh;">
    <div class="col-md-12">
        
        <div  style="margin-top: 100px;display: flex;justify-content: center;">
            <h2>Teachers List</h2>
        </div>
        <div class=" ">
            <table class="table table-bordered table-primary table-hover table-striped">
                <thead class="thead-dark text-center">
                    <tr>
                        <th>SL No.</th>
                        <th>ID</th>
                        <th>Teacher Name</th>
                        <th>Class</th>
                        <th>Division</th>
                       
                    </tr>
                </thead>
                <tbody class="text-center">
                    {% for teacher in teachers_list %}
                    <tr>
                         
                        <td>{{forloop.counter }}</td>
                        <td>{{ teacher.teacher_id}}</td>
                        <td>{{ teacher.teacher_name | title }}</td>
                        <td>{{ teacher.teacher_class | capfirst }}</td>
                        <td>{{ teacher.division | title }}</td>
                        
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
 
 

    <script>
        setTimeout(function() {
           var errorMsg = document.getElementById('error-msg');
           if (errorMsg) {
              errorMsg.style.display = 'none';
           }
        }, 2000); // 5000 milliseconds = 5 seconds
     </script>
</div>
{% endblock %}